# https://travis-ci.org/cesarcruz/fotuto
language: python

services: postgresql

python:
  - "2.7"

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.cache/pip

addons:
  code_climate:
    repo_token: f1b563be21111d6d3c19acb030ecceb3b64fb32bd1dff03e89d60eca745b62c8

before_install:
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install psycopg2
  - pip install coveralls

before_script:
  - psql -c 'create database fotuto;' -U postgres
  - cp fotuto/settings_local.py.example fotuto/settings_local.py
  - export DJANGO_SETTINGS_MODULE=fotuto.settings
  - python manage.py migrate --noinput
  - npm install karma-cli karma-jasmine karma-phantomjs-launcher
  - npm install protractor@2
  - webdriver-manager update --standalone
  - npm install -g bower
  - bower install
  - python manage.py runserver &

  # Configure firefox for Selenium tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://selenium-release.storage.googleapis.com/2.52/selenium-server-standalone-2.52.0.jar"
  - "java -jar selenium-server-standalone-2.52.0.jar > /dev/null &"

script:
  - coverage run --source=fotuto manage.py test
  - karma start static/spa/karma.conf.js --single-run --browsers PhantomJS
  - ./functional_tests/spa-tests.sh config
  - protractor static/spa/protractor.conf.js --capabilities.browserName firefox

after_script:
  - ./functional_tests/spa-tests.sh clean

after_success:
  - codecov
  - coveralls