# https://travis-ci.org/cesarcruz/fotuto
language: python

services: postgresql

python:
  - "2.7"

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - pip install codecov

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install psycopg2

before_script:
  - psql -c 'create database fotuto;' -U postgres
  - cp fotuto/settings_local.py.example fotuto/settings_local.py
  - export DJANGO_SETTINGS_MODULE=fotuto.settings
  - python manage.py migrate --noinput
  - npm install -g bower
  - bower install

  # Configure firefox for Selenium tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "wget http://selenium-release.storage.googleapis.com/2.52/selenium-server-standalone-2.52.0.jar"
  - "java -jar selenium-server-standalone-2.52.0.jar > /dev/null &"

script:
  - python manage.py test

after_success:
  - codecov